{% set name = "pygcn" %}
{% set version = "1.1.3" %}
{% set sha256 = "cc74d365e9b53bd909ec7c4c0d36badf327c848f1481909669f099526fde66dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  entry_points:
    - pygcn-listen = gcn.cmdline:listen_main
    - pygcn-serve = gcn.cmdline:serve_main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=3.4
    - wheel
  run:
    - lxml
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - gcn
    - gcn.handlers
    - gcn.notice_types
    - gcn.voeventclient
  commands:
    - python -m pip check
    - python -m pytest --pyargs gcn
    - pygcn-listen --help
    - pygcn-serve --help

about:
  home: https://github.com/lpsinger/pygcn
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.md
  summary: Anonymous VOEvent client for receiving GCN/TAN notices in XML format
  description: |
    The Gamma-ray Coordinates Network/Transient Astronomy Network (GCN/TAN),
    is a system for distributing astronomical alerts, largely focused on
    operations of and detections from high-energy satellite missions.

    GCN/TAN disseminates both Notices (prompt, machine-readable alerts) and
    Circulars (human-readable correspondence) through a handful of delivery
    methods and formats.

    This package implements a simple client that anonymously listens for
    VOEvent XML format notices over the custom TCP/IP VOEvent Transport
    Protocol.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
