{% set name = "pygcn" %}
{% set version = "1.0.0" %}
{% set sha256 = "34a5387572a7f8dfd7639cb944a768fa86ab1703eef0c28bf553785e15275aab" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vvv"
  entry_points:
    - pygcn-listen = gcn.cmdline:listen_main
    - pygcn-serve = gcn.cmdline:serve_main

requirements:
  host:
    - python
    - pip
    - setuptools >=30.3.0
  run:
    - python
    - lxml
    - six

test:
  imports:
    - gcn
    - gcn.handlers
    - gcn.notice_types
    - gcn.voeventclient
  requires:
    - pytest
  commands:
    - pygcn-listen --help
    - pygcn-serve --help
    - python -m pytest --pyargs gcn

about:
  home: https://github.com/lpsinger/pygcn
  license: GPLv2+
  license_family: GPL
  license_file: COPYING
  summary: Anonymous VOEvent client for receiving GCN/TAN notices in XML format
  description: |
    The Gamma-ray Coordinates Network/Transient Astronomy Network (GCN/TAN),
    is a system for distributing astronomical alerts, largely focused on
    operations of and detections from high-energy satellite missions.

    GCN/TAN disseminates both Notices (prompt, machine-readable alerts) and
    Circulars (human-readable correspondence) through a handful of delivery
    methods and formats.

    This package implements a simple client that anonymously listens for
    VOEvent XML format notices over the custom TCP/IP VOEvent Transport
    Protocol.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - lpsinger
