travis:
  secure:
    BINSTAR_TOKEN: c4EJM8JM6E8eNEGwgXo95lGRojFuEgZW1RYClnYYtD7dvA9nYTbC7sIyYdda1N66fyPMr+TAsxsInY+JBYBHEONO/z7NneXGM2zgTbLv3gnlOcKrRKNQ5R/PJyfKNuaEv1ndyeSijU5H3oN/hzlR9+db3titzygTSOVruG0L0TehWd1TXzUb/3a1CPEnIU2hSwttx+w2CeLHsfmmrcB+nDpEZv7cdwGTw5F21pRYof19Zu/L9TFgfi3hviJqGjs0nw2bD109AVzyTzrL4hpI6GpJIIfPCjWLhaU9dG6pgyK3c3IhS/7snBn40km1P2G/bLCouCEOALV4WkfOmw+vlWyyrHRtYlCilQ6kKIA13hcwmbyAyPD49Pgc4BHyIJ0XWhIYS2AhvMdR/6LzkmzKOGJymNILmlGYH2AA8pbIQmdIJXGT4M7c2nRpY3q4jDSl7FAheVR9HxsHkOu/YFbEACxq/E/OxNfEjhZEjBYaTxNESDq5UkBe/ghfw9a+qpL9j5JHWS4snb72jesPNzoG6m+yXkaaM3cb/r08QYq5GT3jZDtMdiL/pcf4a9KHE20Q6QGKOSnSjucbs6VaRYCuW3MLchWak+/dsqdek7bConJ/puYcRWkmnIQZr5e6v9rezVXVn4tiATGs0DqNSrO403IbacptMi4HqKh8uC8icJ8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
